In [1]:
# ws5
import pandas as pd
uri = 'data/sale_quarterly1.xlsx'
cols = 'b:e'
df = pd.read_excel(uri, sheet_name='Sheet1', usecols=cols, header=2)
df.head(4)

     Employee  Sales  Quarter  Country
0       ณิแนน   1000        1       US
1  กอบเกียรติ    300        1  ญี่ปุ่น
2        Tina    400        1      ไทย
3       Maria    500        1       UK

In [2]:
df.shape

(20, 4)

In [3]:
df.dtypes

Employee    object
Sales        int64
Quarter      int64
Country     object
dtype: object

In [ ]:
df.describe()

             Sales    Quarter
count    20.000000  20.000000
mean    570.500000   2.500000
std     349.186649   1.147079
min      50.000000   1.000000
25%     287.500000   1.750000
50%     600.000000   2.500000
75%     900.000000   3.250000
max    1000.000000   4.000000

In [16]:
# 
uri = 'data/sale_quarterly1.xlsx'
cols = 'b:e'
df = pd.read_excel(uri, sheet_name='Sheet1', usecols=cols, header=2, 
                   dtype={'Quarter':str})
df.head()
df.describe()

             Sales
count    20.000000
mean    570.500000
std     349.186649
min      50.000000
25%     287.500000
50%     600.000000
75%     900.000000
max    1000.000000

In [6]:
df.Quarter = df.Quarter.astype('category')
df.dtypes

Employee      object
Sales          int64
Quarter     category
Country       object
dtype: object

In [7]:
df.describe()

             Sales
count    20.000000
mean    570.500000
std     349.186649
min      50.000000
25%     287.500000
50%     600.000000
75%     900.000000
max    1000.000000

In [8]:
df.Sales.sum()

np.int64(11410)

In [13]:
# df.head()
# df.mean()
# df.std()
# df.max()
# df.min()
df.sum(numeric_only=True)

Sales    11410
dtype: int64

In [14]:
# ws6
pvt = df.pivot_table(index='Quarter') 
pvt = df.pivot_table(index='Quarter', margins=True) 
pvt

C:\Users\USER\AppData\Local\Temp\ipykernel_38240\1033178138.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pvt = df.pivot_table(index='Quarter')

TypeError: agg function failed [how->mean,dtype->object]

In [15]:
df.groupby('Quarter').mean(numeric_only=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_38240\403914973.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Quarter').mean(numeric_only=True)

         Sales
Quarter
1        600.0
2        462.0
3        630.0
4        590.0

In [12]:
# ws7 
pvt = df.pivot_table(index=['Quarter','Employee'] , margins=True) # mean  , margins=True
pvt

C:\Users\USER\AppData\Local\Temp\ipykernel_38240\2812208478.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pvt = df.pivot_table(index=['Quarter','Employee'] , margins=True) # mean  , margins=True

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
# ws8 

import numpy as np

pvt = df.pivot_table(index=['Quarter'], aggfunc=np.sum, margins=True) 
pvt = df.pivot_table(index=['Quarter'], aggfunc='sum', margins=True) 
pvt = df.pivot_table(index=['Quarter'], values='Sales', aggfunc='sum', margins=True) 
# pvt.applymap("THB{0:,.2f}".format) 
pvt = pvt.applymap("{0:,}".format) 
# pvt.style.format({'Sales': "{:,.2f}"}) 
pvt

In [ ]:
df.groupby('Quarter').sum()
# df.groupby(['Country','Quarter']).sum()

In [ ]:
# ws9
# pvt = df.pivot_table(index=['Quarter'], values=['Sales'],
#         aggfunc=['sum','mean'], margins=True)
#
pvt = df.pivot_table(index=['Quarter'], values=['Sales'],
        aggfunc=['sum','max','min','mean'], margins=True)

pvt

In [ ]:
df['Import'] = df['Sales']  - 50
display(df.head())
df.head()

In [ ]:
pvt = df.pivot_table(index=['Quarter'], values=['Sales','Import'],
        aggfunc={'Sales':'sum','Import':'mean'}, margins=True)

pvt

In [ ]:
# ws10
pvt = df.pivot_table(index=['Quarter'], values='Sales', aggfunc='sum') 
pvt = pvt.applymap("{0:,}".format) 
# pvt.sort_values('Sales')
pvt = pvt.sort_values('Sales', ascending=False)
## pvt.Sales.sort_values()
pvt

In [ ]:
# ws11
%matplotlib inline
pvt = df.pivot_table(index=['Quarter'], values='Sales', aggfunc='sum') # 
pvt.plot.bar()


# pvt.sort_values('Sales')
pvt_sorted = pvt.sort_values('Sales', ascending=False)
pvt_sorted.plot.bar()

In [ ]:
# ws12 
import matplotlib.pyplot as plt
plt.rc('font', family='tahoma')

pvt = df.pivot_table(index=['Employee'], values=['Sales'], aggfunc='sum')
# pvt.sort_values(['Sales'], ascending=[0])
# pvt.sort_values('Sales', ascending=False)
pvt.plot.bar()
pvt

In [ ]:
# ws13
pvt = df.pivot_table(index=['Country'], values=['Sales'], aggfunc='sum')

# pvt.sort_values(['Sales'],ascending=[False])  # ceo blt : top by country
pvt.plot.bar()
plt.title("Sales report")
pvt

In [ ]:
pvt = df.pivot_table(index=['Country','Quarter'], values='Sales', aggfunc='sum')
pvt.plot.bar()
pvt

In [ ]:
# ws14
# for graph
pvt2 = df.pivot_table(index=['Country'], columns=['Quarter'], values=['Sales'], aggfunc='sum', 
                fill_value=0)
pvt2.plot.bar()

# for table
pvt = df.pivot_table(index=['Country'], columns=['Quarter'], values=['Sales'], aggfunc='sum', 
                fill_value=0, margins=True)
pvt = pvt.applymap("{0:,}".format) # 
pvt

In [ ]:
# 
# for table
pvt = df.pivot_table(index=['Country'], columns=['Quarter'], values=['Sales'], aggfunc='sum', 
                fill_value=0, margins=True)

# for graph
g = pvt.drop('All') 
g.drop('All', level=1, axis=1, inplace=True) 
g.plot.bar()

pvt = pvt.applymap("{0:,}".format) #
pvt

In [ ]:
# ws15
# for graph
pvt2 = df.pivot_table(index=['Country'], columns=['Employee'], values=['Sales'], aggfunc='sum', 
                fill_value=0)
pvt2.plot.bar()

# for table
pvt = df.pivot_table(index=['Country'], columns=['Employee'], values=['Sales'], aggfunc='sum', 
                fill_value=0, margins=True)
pvt = pvt.applymap("{0:,}".format) # 
pvt

In [ ]:
# ws15

# for graph
pvt2 = df.pivot_table(index=['Quarter'], columns=['Country'], values=['Sales'], aggfunc='sum', 
                fill_value=0)
pvt2.plot.bar()

# for table
pvt = df.pivot_table(index=['Quarter'], columns=['Country'], values=['Sales'], aggfunc='sum', 
                fill_value=0, margins=True)
pvt = pvt.applymap("{0:,}".format) # ok
pvt

In [ ]:
# 
# for graph
pvt2 = df.pivot_table(index=['Employee'], columns=['Country'], values=['Sales'], aggfunc='sum', 
                fill_value=0)
pvt2.plot.bar()

# for table
pvt = df.pivot_table(index=['Employee'], columns=['Country'], values=['Sales'], aggfunc='sum', 
                fill_value=0, margins=True)
pvt = pvt.applymap("{0:,}".format) # ok
pvt

In [ ]:
# ws16

# for graph
pvt2 = df.pivot_table(index=['Employee'], columns=['Quarter'], values=['Sales'], aggfunc='sum', 
                fill_value=0)
pvt2.plot.bar()

# for table
pvt = df.pivot_table(index=['Employee'], columns=['Quarter'], values=['Sales'], aggfunc='sum', 
                fill_value=0, margins=True)
pvt = pvt.applymap("{0:,}".format) # 
pvt

In [ ]:
#
# for graph
pvt2 = df.pivot_table(index=['Country'], columns=['Quarter'], values=['Sales'], aggfunc='count', 
                fill_value=0)
pvt2.plot.bar()

# for table
pvt = df.pivot_table(index=['Country'], columns=['Quarter'], values=['Sales'], aggfunc='count', 
                fill_value=0, margins=True)
pvt = pvt.applymap("{0:,}".format) # ok
pvt

In [ ]:
df.dtypes
df.Quarter = df.Quarter.astype('int')

In [ ]:
# ws17
pvt = df[df.Quarter == 3].pivot_table(index='Country',columns='Quarter',values='Sales', 
                                      aggfunc='sum')
pvt

In [ ]:
pvt = df[(df.Quarter == 3) & 
         (df.Sales >= 100)].pivot_table(index='Country', 
                      columns='Quarter',values='Sales',aggfunc='sum')
pvt

In [ ]:
pvt = df[(df.Quarter == 3) | (df.Quarter == 1)].pivot_table(index='Country',
                                columns='Quarter',values='Sales',aggfunc='sum')
pvt

In [ ]:
pvt = df[df.Country.str.match('U')].pivot_table(index='Country',columns='Quarter',values='Sales') #fill_value=0
pvt

In [ ]:
pvt = df[df.Country=='US'].pivot_table(index='Country',columns='Quarter',values='Sales') #fill_value=0
pvt

In [ ]:
# ws18
# for graph
pvt2 = df[(df.Employee.str.match('กอบ')) | 
         (df.Employee.str.match('Bill'))].pivot_table(
    index='Employee',columns=['Quarter'],values='Sales',fill_value=0, 
    aggfunc='sum')
pvt2.plot.bar()

# for data
pvt = df[(df.Employee.str.match('กอบ')) | 
         (df.Employee.str.match('Bill'))].pivot_table(
    index='Employee',columns=['Quarter'],values='Sales',fill_value=0, 
    aggfunc='sum', margins=True)

pvt